version: '3.4'
services:

  chatgpt:
    image: admibo/chatgpt-robot
    restart: always
    ports:
      - 5001:5001
    environment:
      LANG: 'C.UTF-8'
    networks:
      - ai-robot
    volumes:
      - ./config.cfg:/app/config.cfg
      - ./data:/app/data
      - ./presets:/app/presets
    depends_on:
      - gemini-openai-proxy

  gemini-openai-proxy:
    image: ghcr.io/zuisong/gemini-openai-proxy:deno
    restart: always
    networks:
      - ai-robot


networks:
  ai-robot:
